In [1]:
import pandas as pd
import numpy as np

In [2]:
mypickle = pd.read_pickle("uncertainty_epoch80_labelled21300.pkl")
excelfile = "uncertainty_epoch80_labelled21300.xlsx"

In [3]:
mypickle
uncertainty = mypickle['uncertainty']
oracle_indices = mypickle['oracle_indices']
labelled_map = mypickle['labelled_map']

In [4]:
len(oracle_indices) # 150000
oracle_indices

array([ 57286, 104942,  86483, ...,  18125,  68125,  24719], dtype=int64)

In [5]:
print(len(uncertainty))
uncertainty

150000


array([0.01699404, 0.00845005, 0.00102425, ..., 0.11669621, 0.07163577,
       0.13702059], dtype=float32)

In [6]:
original = uncertainty[0:50000-1]
aug1 = uncertainty[50000:100000-1]
aug2 = uncertainty[100000:150000-1]

In [24]:
len(aug2)

49999

In [8]:
uncertainty_length = len(uncertainty)
if uncertainty_length == 100000:
    matrix = np.vstack([original,aug1])
if uncertainty_length == 150000:    
    matrix = np.vstack([original,aug1,aug2])
#matrix = np.vstack([original,aug1])
#matrix     = np.transpose(matrix_aux)
df_lab_img = pd.DataFrame(matrix)

In [9]:
df_lab_img

0         1         2         3         4         5         6      \
0  0.016994  0.008450  0.001024  0.000316  0.000014  0.060194  0.129119   
1  0.020997  0.002147  0.000179  0.002526  0.001095  0.057168  0.117601   
2  0.040864  0.002540  0.001851  0.000303  0.000123  0.149709  0.079170   

      7         8         9      ...     49989     49990     49991     49992  \
0  0.000601  0.003817  0.169960  ...  0.000312  0.258320  0.036453  0.036856   
1  0.000518  0.014382  0.152027  ...  0.010312  0.103035  0.021093  0.007875   
2  0.119786  0.081959  0.187783  ...  0.002284  0.177339  0.034937  0.090787   

      49993     49994     49995     49996     49997     49998  
0  0.048701  0.095779  0.051191  0.120648  0.136553  0.036120  
1  0.104311  0.059962  0.066966  0.248387  0.086192  0.023786  
2  0.038218  0.055336  0.112343  0.160828  0.116696  0.071636  

[3 rows x 49999 columns]

In [10]:
df_lab_img.std()
df_lab_img = pd.DataFrame(np.vstack([matrix, df_lab_img.std()]))

In [11]:
df_lab_img.std()

0        0.012430
1        0.002914
2        0.000689
3        0.001051
4        0.000495
           ...   
49994    0.030133
49995    0.034353
49996    0.077080
49997    0.048532
49998    0.022400
Length: 49999, dtype: float32

In [12]:
uncertainties_std = df_lab_img.transpose()

In [13]:
uncertainties_std

0         1         2         3
0      0.016994  0.020997  0.040864  0.012783
1      0.008450  0.002147  0.002540  0.003531
2      0.001024  0.000179  0.001851  0.000836
3      0.000316  0.002526  0.000303  0.001280
4      0.000014  0.001095  0.000123  0.000595
...         ...       ...       ...       ...
49994  0.095779  0.059962  0.055336  0.022136
49995  0.051191  0.066966  0.112343  0.031748
49996  0.120648  0.248387  0.160828  0.065317
49997  0.136553  0.086192  0.116696  0.025367
49998  0.036120  0.023786  0.071636  0.024843

[49999 rows x 4 columns]

In [14]:
if uncertainty_length == 100000:
    uncertainties_std.columns = ['original', 'aug1', 'std']
if uncertainty_length == 150000:    
    uncertainties_std.columns = ['original', 'aug1', 'aug2', 'std']

In [15]:
uncertainties_std

original      aug1      aug2       std
0      0.016994  0.020997  0.040864  0.012783
1      0.008450  0.002147  0.002540  0.003531
2      0.001024  0.000179  0.001851  0.000836
3      0.000316  0.002526  0.000303  0.001280
4      0.000014  0.001095  0.000123  0.000595
...         ...       ...       ...       ...
49994  0.095779  0.059962  0.055336  0.022136
49995  0.051191  0.066966  0.112343  0.031748
49996  0.120648  0.248387  0.160828  0.065317
49997  0.136553  0.086192  0.116696  0.025367
49998  0.036120  0.023786  0.071636  0.024843

[49999 rows x 4 columns]

In [16]:
uncertainties_std.to_excel(excelfile)

Test

In [17]:
len(uncertainty)

150000

In [18]:
len(df_lab_img.std())

49999

In [19]:
std_array = df_lab_img.std()
uncertainty2 = uncertainty
for i in range(len(uncertainty)): # 150000
  uncertainty2[i] = std_array[i % (50000-1)]

In [20]:
print(uncertainty2[0])
print(uncertainty2[49999])
print(uncertainty2[99998])

print(uncertainty2[1])
print(uncertainty2[50000])
print(uncertainty2[99999])

0.012430462
0.012430462
0.012430462
0.0029142254
0.0029142254
0.0029142254


In [21]:
oracle_indices = np.argsort(uncertainty2)

In [22]:
oracle_indices

array([107284,  57285,   7286, ..., 118123,  68124,  18125], dtype=int64)

In [23]:
labelled_map

array([    0,  8196,     0, ...,     0,     0, 10933], dtype=int64)